/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--theme-background) / <alpha-value>)',
        'content1': 'hsl(var(--theme-content1) / <alpha-value>)',
        'content2': 'hsl(var(--theme-content2) / <alpha-value>)',
        'content3': 'hsl(var(--theme-content3) / <alpha-value>)',
        'content4': 'hsl(var(--theme-content4) / <alpha-value>)',
        'foreground': 'hsl(var(--theme-foreground) / <alpha-value>)',
        'foreground-50': 'hsl(var(--theme-foreground-50) / <alpha-value>)',
        'foreground-100': 'hsl(var(--theme-foreground-100) / <alpha-value>)',
        'foreground-200': 'hsl(var(--theme-foreground-200) / <alpha-value>)',
        'foreground-300': 'hsl(var(--theme-foreground-300) / <alpha-value>)',
        'foreground-400': 'hsl(var(--theme-foreground-400) / <alpha-value>)',
        'foreground-500': 'hsl(var(--theme-foreground-500) / <alpha-value>)',
        'foreground-600': 'hsl(var(--theme-foreground-600) / <alpha-value>)',
        'foreground-700': 'hsl(var(--theme-foreground-700) / <alpha-value>)',
        'foreground-800': 'hsl(var(--theme-foreground-800) / <alpha-value>)',
        'foreground-900': 'hsl(var(--theme-foreground-900) / <alpha-value>)',
        'default': 'hsl(var(--theme-default) / <alpha-value>)',
        'default-foreground': 'hsl(var(--theme-default-foreground)',
        'default-50': 'hsl(var(--theme-default-50) / <alpha-value>)',
        'default-100': 'hsl(var(--theme-default-100) / <alpha-value>)',
        'default-200': 'hsl(var(--theme-default-200) / <alpha-value>)',
        'default-300': 'hsl(var(--theme-default-300) / <alpha-value>)',
        'default-400': 'hsl(var(--theme-default-400) / <alpha-value>)',
        'default-500': 'hsl(var(--theme-default-500) / <alpha-value>)',
        'default-600': 'hsl(var(--theme-default-600) / <alpha-value>)',
        'default-700': 'hsl(var(--theme-default-700) / <alpha-value>)',
        'default-800': 'hsl(var(--theme-default-800) / <alpha-value>)',
        'default-900': 'hsl(var(--theme-default-900) / <alpha-value>)',
        'primary': 'hsl(var(--theme-primary) / <alpha-value>)',
        'primary-50': 'hsl(var(--theme-primary-50) / <alpha-value>)',
        'primary-100': 'hsl(var(--theme-primary-100) / <alpha-value>)',
        'primary-200': 'hsl(var(--theme-primary-200) / <alpha-value>)',
        'primary-300': 'hsl(var(--theme-primary-300) / <alpha-value>)',
        'primary-400': 'hsl(var(--theme-primary-400) / <alpha-value>)',
        'primary-500': 'hsl(var(--theme-primary-500) / <alpha-value>)',
        'primary-600': 'hsl(var(--theme-primary-600) / <alpha-value>)',
        'primary-700': 'hsl(var(--theme-primary-700) / <alpha-value>)',
        'primary-800': 'hsl(var(--theme-primary-800) / <alpha-value>)',
        'primary-900': 'hsl(var(--theme-primary-900) / <alpha-value>)',
        'secondary': 'hsl(var(--theme-secondary) / <alpha-value>)',
        'secondary-50': 'hsl(var(--theme-secondary-50) / <alpha-value>)',
        'secondary-100': 'hsl(var(--theme-secondary-100) / <alpha-value>)',
        'secondary-200': 'hsl(var(--theme-secondary-200) / <alpha-value>)',
        'secondary-300': 'hsl(var(--theme-secondary-300) / <alpha-value>)',
        'secondary-400': 'hsl(var(--theme-secondary-400) / <alpha-value>)',
        'secondary-500': 'hsl(var(--theme-secondary-500) / <alpha-value>)',
        'secondary-600': 'hsl(var(--theme-secondary-600) / <alpha-value>)',
        'secondary-700': 'hsl(var(--theme-secondary-700) / <alpha-value>)',
        'secondary-800': 'hsl(var(--theme-secondary-800) / <alpha-value>)',
        'secondary-900': 'hsl(var(--theme-secondary-900) / <alpha-value>)',
        'danger': 'hsl(var(--theme-danger) / <alpha-value>)',
        'danger-50': 'hsl(var(--theme-danger-50) / <alpha-value>)',
        'danger-100': 'hsl(var(--theme-danger-100) / <alpha-value>)',
        'danger-200': 'hsl(var(--theme-danger-200) / <alpha-value>)',
        'danger-300': 'hsl(var(--theme-danger-300) / <alpha-value>)',
        'danger-400': 'hsl(var(--theme-danger-400) / <alpha-value>)',
        'danger-500': 'hsl(var(--theme-danger-500) / <alpha-value>)',
        'danger-600': 'hsl(var(--theme-danger-600) / <alpha-value>)',
        'danger-700': 'hsl(var(--theme-danger-700) / <alpha-value>)',
        'danger-800': 'hsl(var(--theme-danger-800) / <alpha-value>)',
        'danger-900': 'hsl(var(--theme-danger-900) / <alpha-value>)',
        'warning': 'hsl(var(--theme-warning) / <alpha-value>)',
        'warning-50': 'hsl(var(--theme-warning-50) / <alpha-value>)',
        'warning-100': 'hsl(var(--theme-warning-100) / <alpha-value>)',
        'warning-200': 'hsl(var(--theme-warning-200) / <alpha-value>)',
        'warning-300': 'hsl(var(--theme-warning-300) / <alpha-value>)',
        'warning-400': 'hsl(var(--theme-warning-400) / <alpha-value>)',
        'warning-500': 'hsl(var(--theme-warning-500) / <alpha-value>)',
        'warning-600': 'hsl(var(--theme-warning-600) / <alpha-value>)',
        'warning-700': 'hsl(var(--theme-warning-700) / <alpha-value>)',
        'warning-800': 'hsl(var(--theme-warning-800) / <alpha-value>)',
        'warning-900': 'hsl(var(--theme-warning-900) / <alpha-value>)',
        'success': 'hsl(var(--theme-success) / <alpha-value>)',
        'success-50': 'hsl(var(--theme-success-50) / <alpha-value>)',
        'success-100': 'hsl(var(--theme-success-100) / <alpha-value>)',
        'success-200': 'hsl(var(--theme-success-200) / <alpha-value>)',
        'success-300': 'hsl(var(--theme-success-300) / <alpha-value>)',
        'success-400': 'hsl(var(--theme-success-400) / <alpha-value>)',
        'success-500': 'hsl(var(--theme-success-500) / <alpha-value>)',
        'success-600': 'hsl(var(--theme-success-600) / <alpha-value>)',
        'success-700': 'hsl(var(--theme-success-700) / <alpha-value>)',
        'success-800': 'hsl(var(--theme-success-800) / <alpha-value>)',
        'success-900': 'hsl(var(--theme-success-900) / <alpha-value>)',
      }
    },
  },
  plugins: [],
}
